version: '2'

services:
  redis:
    image: 'redislabs/rejson:latest'
    command: redis-server --save 900 1 --save 300 10 --save 60 10000 --loadmodule /usr/lib/redis/modules/rejson.so
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    labels:
      kompose.service.type: nodeport
    ports:
      - '6379:6379'
